### ISSUE TITLE
Does it also work when used with MenuItem?

### ISSUE THREAD

**Issue by SwederSchellens** [dominikbulaj/react-scroll-into-view#11]
Hi,

Thanks for providing this great component. 

I have it working when used with Button. But I would like to also use it with  [MaterialUI MenuItem](https://material-ui.com/api/menu-item/) but so far I did't get it to work. Is it supposed to work with MenuItem?

Cheers.

**Comment by dominikbulaj** [comment]
@SwederSchellens you mean [MaterialUI MenuItem](https://material-ui.com/api/menu-item/)?

**Comment by SwederSchellens** [comment]
Yes. Sorry for not being clear about that.

**Comment by dominikbulaj** [comment]
Yeah, it's not possible at the moment. I'm gonna expose `onClick` property that will help resolve this and similar issues.

**Comment by dominikbulaj** [comment]
@SwederSchellens I've added `onClick` callback in v1.7.0
Please see this example https://codesandbox.io/s/loving-cookies-6no9o
