### ISSUE TITLE
Could not find a declaration file for module 'react-scroll-into-view'. 

### ISSUE THREAD

**Issue by linareyne** [dominikbulaj/react-scroll-into-view#12]
Getting this error from an npm install

Could not find a declaration file for module 'react-scroll-into-view'. '/node_modules/react-scroll-into-view/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-scroll-into-view` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-scroll-into-view';`

**Comment by dominikbulaj** [comment]
Hi 

this is about missing TypeScript types definitions. At the moment I don't provide them as library code is vanilla JavaScript. 

I'll try to add them in the following days. 
Thank you for your patience

**Comment by dominikbulaj** [comment]
Added in v1.8.0
