### ISSUE TITLE
Radio button label click shows error and does not selects radio button.

### ISSUE THREAD

**Issue by prasannak-iprogrammer** [dominikbulaj/react-scroll-into-view#17]
I have wrapped my FormControlLabel component into <ScrollIntoView selector="#footer">....</ScrollIntoView>.

When I click on radio circle it works fine. But when I use to click on radio button label. It shows error on google chrome as,
ERROR : Uncaught TypeError: Cannot read property 'scrollIntoView' of null

And in such case, my radio button is also un-selected.

**Comment by dominikbulaj** [comment]
Hi @prasannak-iprogrammer  could you share code snippet. 
I suppose it's something like:

```javascript
import ScrollIntoView from 'react-scroll-into-view'
// ...

const MyElement = () => {
  return <ScrollIntoView selector="...">
    <FormControlLabel value="..." control={<Radio />} label="..." />
  </ScrollIntoView>
}
```

But it's just a guess, so code snippet would help to see what causes the issue

**Comment by dominikbulaj** [comment]
Closing. Feedback required. Feel free to reopen when more details are added
