### ISSUE TITLE
This always scroll to middle of the target DOM

### ISSUE THREAD

**Issue by shortgiraffe4** [dominikbulaj/react-scroll-into-view#2]
Maybe it's your intention but at least give me an option to scroll to the head (start) of the target DOM.
Really appreciate it. If you don't have time, maybe I can help with an PR.

**Comment by dominikbulaj** [comment]
@shortgiraffe4 thanks. I will add today :)

**Comment by dominikbulaj** [comment]
Done with v1.3.1 Demo: https://codesandbox.io/s/30wkq459j5 Feel free to open new issue if something more is required/missing :)
