### ISSUE TITLE
Feature Request - Add Offset to Scroll

### ISSUE THREAD

**Issue by wdfinch** [dominikbulaj/react-scroll-into-view#25]
Hi there, thanks so much for making this library. It works great and is super lightweight. I was wondering if it would be possible to add an offset option so we could scroll to a target with some offset added to the final destination. Thanks!

**Comment by dominikbulaj** [comment]
Thanks,
this library works with [element.scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) which doesn't support offset. 
One way to do that is to manually scroll the page to a given place (add offset) within `onClick`, something like this https://codesandbox.io/s/recursing-saha-tiy2m

It's not perfect but at least works. 

Let me know, what do you think @wdfinch

**Comment by wdfinch** [comment]
Ok thanks. Yes, there are fine work arounds. I just thought it would be convenient if it could be supported out of the box,
