### ISSUE TITLE
react-scroll-into-view not working next.js app

### ISSUE THREAD

**Issue by dhavalveera** [dominikbulaj/react-scroll-into-view#26]
Hello,

I am trying to use this useful npm package with my `Next.js` based App but when I run the code, it throws an exception that `SyntaxError: Cannot use import statement outside a module`

![image](https://user-images.githubusercontent.com/32231977/141680538-6990d35c-f6db-4e74-86d3-e466b3effa79.png)

for your reference & better understanding, I am attaching the screenshot of the exception/error I am encountering when using it in Next.js -  a React.js Framework

please help me in this case.

@dominikbulaj

**Comment by dominikbulaj** [comment]
Hi @dhavalveera 
I found a similar [issue in another library](https://github.com/asyncapi/asyncapi-react/issues/177#issuecomment-729823940) and there is a solution for this - use [dynamic import without sso](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) (as react-scroll-into-view works only in a browser).

I've made codesandbox for you where it actually works - https://codesandbox.io/s/focused-silence-ylc3e?file=/pages/index.js

**Comment by dhavalveera** [comment]
> Hi @dhavalveera I found a similar [issue in another library](https://github.com/asyncapi/asyncapi-react/issues/177#issuecomment-729823940) and there is a solution for this - use [dynamic import without sso](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) (as react-scroll-into-view works only in a browser).
> 
> I've made codesandbox for you where it actually works - https://codesandbox.io/s/focused-silence-ylc3e?file=/pages/index.js

Thank you sir for your quick help and now it is working perfectly fine for me. Thanks a lot @dominikbulaj
