### ISSUE TITLE
Styles does not applies

### ISSUE THREAD

**Issue by vademyanchik** [dominikbulaj/react-scroll-into-view#3]
Hi, styles does not applies, you can check it's in your example https://codesandbox.io/s/14lxm6jmm7.
I guess problem [here](https://github.com/dominikbulaj/react-scroll-into-view/blob/master/src/index.js#L10), need spreed operator `...style`. Thanks!

**Comment by dominikbulaj** [comment]
@vademyanchik Thanks for catching it. Yes, I missed spread operator by accident. Fixed and published v1.3.2
